/*
* Generated file
*
* Generated from: yang module name: bootstrappingmanager-setup-impl yang module local name: setup-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Mar 19 16:58:44 CET 2018
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.bootstrappingmanager.alternative.setup.impl;
public class SetupModuleFactory extends eu.virtuwind.bootstrappingmanager.alternative.setup.impl.AbstractSetupModuleFactory {

}
