/*
* Generated file
*
* Generated from: yang module name: pathmanager-impl yang module local name: pathmanager-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Feb 06 14:41:29 EET 2017
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.pathmanager.impl;
public class PathManagerModuleFactory extends eu.virtuwind.pathmanager.impl.AbstractPathManagerModuleFactory {

}
