/*
* Generated file
*
* Generated from: yang module name: nbi-impl yang module local name: nbi-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun Mar 26 18:17:05 CEST 2017
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.nbi.impl;
public class NbiModuleFactory extends eu.virtuwind.nbi.impl.AbstractNbiModuleFactory {

}
