/*
* Generated file
*
* Generated from: yang module name: registryhandler-impl yang module local name: registryhandler-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Oct 17 13:50:23 EEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.registryhandler.impl;
public class RegistryHandlerModuleFactory extends eu.virtuwind.registryhandler.impl.AbstractRegistryHandlerModuleFactory {

}
