/*
* Generated file
*
* Generated from: yang module name: resourcemonitor-impl yang module local name: resourcemonitor-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Feb 02 15:24:02 EET 2017
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.resourcemonitor.impl;
public class ResourcemonitorModuleFactory extends eu.virtuwind.resourcemonitor.impl.AbstractResourcemonitorModuleFactory {

}
