/*
* Generated file
*
* Generated from: yang module name: bootstrappingmanager-dhcp-impl yang module local name: example-lease-manager
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Dec 10 10:30:23 CET 2016
*
* Do not modify this file unless it is present under src/main directory
*/
//package eu.virtuwind.bootstrappingmanager.dhcp.impl;
package eu.virtuwind.bootstrappingmanager.alternative.dhcp.impl;

public class ExampleLeaseManagerModuleFactory extends eu.virtuwind.bootstrappingmanager.alternative.dhcp.impl.AbstractExampleLeaseManagerModuleFactory {

}
