/*
* Generated file
*
* Generated from: yang module name: bootstrappingmanager-setup-impl yang module local name: setup-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun Dec 11 16:05:19 CET 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.bootstrappingmanager.setup.impl;
public class SetupModuleFactory extends eu.virtuwind.bootstrappingmanager.setup.impl.AbstractSetupModuleFactory {

}
